language: rust
rust:
  - stable
cache: cargo
before_script:
  - |
      cargo install --force cargo-travis &&
      export PATH=$HOME/.cargo/bin:$PATH
script:
  - cargo build --verbose --all
  - cargo test --verbose --all
after_success:
# measure code coverage and upload to coveralls.io
  - cargo coveralls
