sudo: false
language: rust
# Dependencies of kcov, used by coverage
addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - binutils-dev
      - cmake
    sources:
      - kalakris-cmake
rust:
  - stable
cache: cargo
before_script:
  - |
      cargo install --force cargo-travis &&
      export PATH=$HOME/.cargo/bin:$PATH
script:
  - cargo build --verbose --all
  - cargo test --verbose --all
after_success:
# measure code coverage and upload to coveralls.io
  - cargo coveralls
